### Add a new review
POST http://localhost:3000/reviews/
Content-Type: application/json
Authorization: Bearer <your_token_here>

{
  "productId": "6751cbc96aac217c1f5aa76e",
  "userId": "6751341f7a01e019ffafb9db",
  "rating": 5,
  "comment": "Excellent product!"
}

### Get all reviews (Admin only)
GET http://localhost:3000/reviews/
Authorization: Bearer <admin_token_here>

### Get reviews by product ID
GET http://localhost:3000/reviews/product/6751cbc96aac217c1f5aa76e

### Get review by ID
GET http://localhost:3000/reviews/6752e6b7c8d2e4a71c3e01f7

### Update review by ID
PUT http://localhost:3000/reviews/6752e6b7c8d2e4a71c3e01f7
Content-Type: application/json
Authorization: Bearer <user_token_here>

{
  "rating": 4,
  "comment": "Updated comment."
}

### Delete review by ID
DELETE http://localhost:3000/reviews/6752e6b7c8d2e4a71c3e01f7
Authorization: Bearer <admin_token_here>
